// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxycudvjjddbzmtsqrdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4eWN1ZHZqamRkYnptdHNxcmRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzEwMjgsImV4cCI6MjA2NDcwNzAyOH0.MQL8OMUm0YMTDYp-kHd5T9ibUPxow8A7cg_yNUb2UVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);